{/*== Icon Imports  == */}
import RightArrowPrimary from "../assets/images/icons/right-arrow-primary.svg";
import RightArrowNextPrimary from "../assets/images/icons/right-arrow-next-primary.svg";
import BulletPointPrimary from "../assets/images/icons/bullet-point-primary.svg";

export const certificationInfo = [
    {
        id: 1,
        title: "Le Parcours de Certification",
        contents: [
            "Le parcours de certification à l’Institut des Métiers du Numérique englobe toutes les étapes nécessaires, depuis l’inscription jusqu’à l’obtention du certificat. Ce parcours est conçu spécialement pour les étudiants inscrits aux formations longue durée du cycle normal."
        ],
        introductionText: null,
        detailedContents: [],
        conclusionText: null,
    },
    {
        id: 2,
        title: "Pour Nous Rejoindre",
        contents: [],
        introductionText: null,
        detailedContents: [
            {
                id: 1,
                title: "Candidature",
                content: "Envoie un message au : **(+229) 01 95 92 23 45** ou un mail à : **admission@imen.school**",
                hasLeadingIcon: true,
                leadingIcon: RightArrowNextPrimary,
                titleUppercase: true,
                titleBold: true,
            },
            {
                id: 2,
                title: "Prends un Rendez-vous d'Orientation Gratuite",
                content: "Viens discuter avec l’un de nos experts en orientation et découvre davantage les métiers du numérique pour choisir une formation qui cadre avec tes aspirations professionnelles.",
                hasLeadingIcon: true,
                leadingIcon: RightArrowNextPrimary,
                titleUppercase: true,
                titleBold: true,
            },
            {
                id: 3,
                title: "Passe ton Test d'Admission",
                content: "En une heure, passe ton test écrit dans nos locaux. Une note de 12/20 est exigée pour être admis à l’IMeN.",
                hasLeadingIcon: true,
                leadingIcon: RightArrowNextPrimary,
                titleUppercase: true,
                titleBold: true,
            },
        ],
        conclusionText: null,
    },
    {
        id: 3,
        title: "Pour s'inscrire",
        contents: [],
        introductionText: "**Fournir le dossier d’inscription composé de :**",
        detailedContents: [
            {
                id: 1,
                title: "01 cartable plastique à rabat de couleur jaune",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: RightArrowPrimary,
                titleUppercase: false,
                titleBold: false,
            },
            {
                id: 2,
                title: "01 chemise dossier de couleur jaune",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: RightArrowPrimary,
                titleUppercase: false,
                titleBold: false,
            },
            {
                id: 3,
                title: "01 copie du dernier diplôme",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: RightArrowPrimary,
                titleUppercase: false,
                titleBold: false,
            },
            {
                id: 4,
                title: "01 copie de la pièce d’identité",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: RightArrowPrimary,
                titleUppercase: false,
                titleBold: false,
            },
            {
                id: 5,
                title: "01 copie de l’acte de naissance",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: RightArrowPrimary,
                titleUppercase: false,
                titleBold: false,
            },
            {
                id: 6,
                title: "02 photos d’identité",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: RightArrowPrimary,
                titleUppercase: false,
                titleBold: false,
            },
            {
                id: 7,
                title: "Fiche d’inscription à retirer au secrétariat",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: RightArrowPrimary,
                titleUppercase: false,
                titleBold: false,
            },
        ],
        conclusionText: "**Payer les frais d’inscription : 20 000 FCFA**",
    },
    {
        id: 4,
        title: "Le Test de Niveau",
        contents: [],
        introductionText: "Deuxième étape du processus d’intégration, ce test évalue :",
        detailedContents: [
            {
                id: 1,
                title: "L’expression écrite",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: BulletPointPrimary,
                titleUppercase: false,
                titleBold: false,
            },
            {
                id: 1,
                title: "La créativité",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: BulletPointPrimary,
                titleUppercase: false,
                titleBold: false,
            },
            {
                id: 1,
                title: "La maîtrise de l’outil informatique",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: BulletPointPrimary,
                titleUppercase: false,
                titleBold: false,
            },
        ],
        conclusionText: "Une **moyenne de 12/20** est exigée pour réussir.",
    },
    {
        id: 5,
        title: "La Reset Week",
        contents: [],
        introductionText: "La **Reset Week** est une semaine d’immersion pour :",
        detailedContents: [
            {
                id: 1,
                title: "Découvrir l’univers du numérique à travers des activités pratiques.",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: BulletPointPrimary,
                titleUppercase: false,
                titleBold: false,
            },
            {
                id: 1,
                title: "Se préparer mentalement et psychologiquement au monde professionnel.",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: BulletPointPrimary,
                titleUppercase: false,
                titleBold: false,
            },
            {
                id: 1,
                title: "Apprendre les bases de l’informatique et interagir avec des professionnels du domaine.",
                content: "",
                hasLeadingIcon: true,
                leadingIcon: BulletPointPrimary,
                titleUppercase: false,
                titleBold: false,
            },
        ],
        conclusionText: null,
    },
    {
        id: 6,
        title: "La Formation",
        contents: [
            "C’est l’étape primordiale du parcours. Pendant la formation, l’étudiant suit et s’implique dans la construction de son savoir à travers des mises en situations pratiques.",
            "Des cours essentiellement pratiques et quelques fois théoriques enseignés par nos experts formateurs. Chaque chapitre ou module de formation bouclé est soldé par la restitution des savoirs, compétences et aptitudes acquis à travers un exercice pratique auquel l’étudiant est soumis. Les notes obtenues au cours de ces évaluations sont comptabilisées et leur somme permet à l’étudiant de valider ou non son parcours de formation.",
        ],
        introductionText: null,
        detailedContents: [],
        conclusionText: null,
    },
    {
        id: 7,
        title: "Le Mois de la Pratique",
        contents: [
            "La réalisation d’un projet est une étape décisive et précède la soutenance. Durant un mois entier, l’étudiant réalise un projet personnel sous la supervision et le guide d’un mentor ou professionnel de son domaine qui lui est spécialement affecté pour l’occasion."
        ],
        introductionText: null,
        detailedContents: [],
        conclusionText: null,
    },
    {
        id: 8,
        title: "La Soutenance",
        contents: [
            "C’est la dernière étape du processus. Elle consiste pour l’étudiant à présenter son projet personnel réalisé devant un jury composé d’experts et de professionnels de son domaine qui apprécieront travail à travers des critères bien définis. La décision de ce jury conditionne la validation ou non du projet de l’étudiant et son admission pour l’obtention du parchemin qu’est le certificat. Une fois l’étape de la certification passée avec succès, l’étudiant obtient son certificat au cours d’une cérémonie officielle."
        ],
        introductionText: null,
        detailedContents: [],
        conclusionText: null,
    },
    {
        id: 9,
        title: "La Certification",
        contents: [
            "La certification représente l'aboutissement ultime pour les étudiants. Elle récompense leurs efforts, leur implication, et leur persévérance tout au long de leur parcours, couronné par une brillante soutenance de projet. L’école organise, pour marquer cet accomplissement, une cérémonie de remise de certificats, où les diplômés reçoivent le parchemin symbolisant leur réussite."
        ],
        introductionText: null,
        detailedContents: [],
        conclusionText: null,
    },
    {
        id: 10,
        title: "Le Stage en Entreprise",
        contents: [
            "Le stage en entreprise constitue une étape clé, aussi essentielle que les autres phases de la certification. Une fois certifiés, les étudiants bénéficient de l’appui de l’IMeN, notamment lors de **La Foire de l’Emploi**, où ils rencontrent les entreprises partenaires pour des entretiens visant leur insertion professionnelle.",
            "Le stage offre une opportunité précieuse : prouver leurs compétences, se démarquer et potentiellement obtenir un contrat de travail. Grâce au **Programme d’Insertion Professionnelle (PIP)** de l’institut, les étudiants sont préparés pour répondre aux attentes du marché et réussir cette transition vers le monde professionnel."
        ],
        introductionText: null,
        detailedContents: [],
        conclusionText: null,
    },
]